In [1]:
import numpy as np
import pandas as pd

In [5]:
d0 = pd.read_csv("~/Documents/galaxy-metabolomics/data-test/fake_data.csv")

In [6]:
d0

,sample,group,N-Acetylglutamine,Coenzyme A,Aminoadipic acid,Fumaric acid,NADH,Valine,Glutathionylspermidine (NPS),dUMP,Uridine 5'-diphosphate,Dodecanoic acid
0,s1,treatment,1367588,4026575,3817,28874,122462,16091,31325,924,22013,2933572
1,s2,treatment,1756666,3182616,13754,27902,177326,17901,27774,755,15450,3055808
2,s3,treatment,1961779,2639077,24914,33249,143268,16874,22768,708,18257,2727629
3,s4,treatment,1601174,3080883,2168,23190,137015,16844,24283,743,15827,2576327
4,s5,treatment,1839876,2159348,6521,31917,142740,18533,28041,819,24483,2638630
5,s6,treatment,1648465,2660196,7496,25704,102614,14211,21603,0,23454,2516917
6,s7,control,1593415,648981,23196,29270,222985,51824,25617,0,19805,3382553
7,s8,control,2073077,571445,9830,30361,242264,44491,41973,0,23291,3260871
8,s9,control,975662,1683377,14920,34064,125776,30540,24562,0,24721,3221197
9,s10,control,1356760,803558,23065,46042,216823,71073,24242,2106,20858,3709770
10,s11,control,863489,2585497,6742,30901,152123,30383,11783,803,28128,3094672
11,s12,control,767455,3072688,19150,29630,142792,37581,32290,1676,34359,3084685